server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  application:
    name: "loans"
  #  config:
  #    import: "configserver:http://localhost:8071/"
  profiles:
    active: "prod"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"